### ISSUE TITLE
Google drive verification code

### ISSUE THREAD

**Issue by Anthony6197** [antoyang/just-ask#13]
Hi,

  I am running the script on a remote cluster which has no gshell cmodule. Instead I am using gdrive. I am wondering could you send me the verification code for downloading the ckpts and data from the google drive address? 

email: ywu4@g.harvard.edu

**Comment by antoyang** [comment]
Hi, gshell does not seem to be supported anymore, but it should be straightforward to go to the Google Drive links following the readme and download the data from there. Another possibility is to use gdown.
