### ISSUE TITLE
Question about the preprocess of LSMDC-FiB dataset

### ISSUE THREAD

**Issue by vateye** [antoyang/just-ask#7]
Hi, I have read your paper "FrozenBiLM". I have several question about the preprocess of LSMDC-FiB dataset. Since I noticed that there are some blanks only contains a part of the word. For example "I went to the place w___e I live." The answer would be "her". Therefore, there exists a problem that the semantic meaning of the question have been destroyed. I am wondering how do you treat these type of questions? 

Thanks.

**Comment by antoyang** [comment]
Hi, I did not do any specific preprocessing for this case. In all cases, I replaced the blank with a [MASK] token.

**Comment by vateye** [comment]
So, you treat the problem as "I went to the place w[MASK]e I live." ?

**Comment by antoyang** [comment]
Yes.

**Comment by vateye** [comment]
Thanks.
