### ISSUE TITLE
Need verification code to download checkpoints and preprocessed features.

### ISSUE THREAD

**Issue by KoDohwan** [antoyang/just-ask#8]
Thanks a lot for sharing great work! 

I've met a problem when downloading pretrained checkpoints, pre-processed data and features via below commands:
```
bash download/download_checkpoints.sh <DEFAULT_CKPT_DIR>
bash download/download_downstream.sh <DEFAULT_DATASET_DIR
```
It requires a verification code and I cannot access to it.
Can you share them another way?

Thank you again for your sharing.

**Comment by antoyang** [comment]
Hi, I have just added the links to the corresponding drive folders directly in the readme.

**Comment by KoDohwan** [comment]
Thanks a lot.
